services:
  flask:
    build: ./
    environment:
      - FLASK_ENV=production
    networks:
      - app-network
    volumes:
      - ./.logs:/app/src/logs

  oauth-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    depends_on:
      - flask
    volumes:
      - ./oauth2-templates:/etc/oauth2-proxy/templates
    ports:
      - "80:4180"
    environment:
      OAUTH2_PROXY_PROVIDER: "google"
      OAUTH2_PROXY_CLIENT_ID: "${CLIENT_ID}"
      OAUTH2_PROXY_CLIENT_SECRET: "${CLIENT_SECRET}"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_UPSTREAMS: "http://flask:8000"
      OAUTH2_PROXY_REDIRECT_URL: "http://127.0.0.1/oauth2/callback"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_COOKIE_SECRET: "${COOKIE_SECRET}"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_COOKIE_DOMAIN: "127.0.0.1"
      OAUTH2_PROXY_CUSTOM_SIGN_IN_LOGO: "/etc/oauth2-proxy/templates/logo.png"
      OAUTH2_PROXY_BANNER: "Trainer Hill - Tagger"
    networks:
      - app-network

networks:
  app-network: